name: GitHub Actions Demo

on: push

jobs:
  gitHub-actions-demo:
    uses: amulyakashyap09/resuable-workflows/.github/workflows/on-push-job.yml@main
  github-actions-input-demo:
    uses: amulyakashyap09/resuable-workflows/.github/workflows/manual-trigger-job.yml@main